name: Angular CI/CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run build

  build-and-push:
    if: github.event_name == 'push'
    needs: lint-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            API_URL=http://${{ secrets.EC2_HOST }}/api
          tags: |
            joseph0070/freelancescope:angular-latest
            joseph0070/freelancescope:angular-${{ github.sha }}
